default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: furima-46405_development
  username: root
  password: ""   # ローカルは空パスワード
  host: localhost

test:
  <<: *default
  database: furima-46405_test
  username: root
  password: ""   # ローカルは空パスワード
  host: localhost

production:
  <<: *default
  database: furima-46405_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

